CREATE SEQUENCE SEQ_ITEM_ATTACHMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE ITEMATTACHMENT (
    ATTACHMENTID NUMBER PRIMARY KEY,
    OWNERTYPE    VARCHAR2(20 CHAR)  NOT NULL,
    ITEMTYPE     VARCHAR2(20 CHAR)  NOT NULL,
    ITEMID       NUMBER             NOT NULL,
    FILENAME     VARCHAR2(255 CHAR) NOT NULL,
    CONTENTTYPE  VARCHAR2(120 CHAR),
    FILEDATA     BLOB               NOT NULL,
    CREATEDAT    DATE DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_ITEMATTACHMENT_ITEM
    ON ITEMATTACHMENT (OWNERTYPE, ITEMTYPE, ITEMID);
