CREATE SEQUENCE SEQ_ASSIGNMENT_SUBMISSION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE ASSIGNMENTSUBMISSION (
    SUBMISSIONID NUMBER PRIMARY KEY,
    OWNERTYPE    VARCHAR2(20 CHAR)  NOT NULL,
    ASSIGNMENTID NUMBER             NOT NULL,
    STUDENTID    VARCHAR2(50 CHAR)  NOT NULL,
    DESCRIPTION  VARCHAR2(1000 CHAR),
    FILENAME     VARCHAR2(255 CHAR),
    CONTENTTYPE  VARCHAR2(120 CHAR),
    FILEDATA     BLOB,
    SUBMITTEDAT  DATE DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_ASSIGNMENT_SUBMISSION_TARGET
    ON ASSIGNMENTSUBMISSION (OWNERTYPE, ASSIGNMENTID);
